import { Suspense } from "hono/jsx/streaming";
import LazyImage from "./lazyImage";

interface Props {
	prompt: string;
	imagine: () => Promise<string>;
}

export default function Imagine({ prompt, imagine }: Props) {
	return (
		<main class="mx-4 my-2 md:mx-24 lg:mx-48 grid gap-4">
			<a href="/">
				<p class="underline">Back to home</p>
			</a>
			<h1 class="text-2xl md:text-3xl lg:text-4xl font-bold">
				Generation result
			</h1>
			<p>Prompt: {prompt}</p>

			<Suspense
				fallback={
					<div>
						<p>
							Generating... (Note: this image was generated by DALL-E3. Not
							SDXL)
						</p>
						<img
							class="mw-3xl animate-bounce animate-pulse"
							src="/assets/placeholder.jpg"
							alt="Loading placeholder"
						/>
					</div>
				}
			>
				<LazyImage class="mw-3xl" lazySrc={imagine} alt={prompt} />
			</Suspense>
		</main>
	);
}
